version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn project_test.wsgi:application --bind 0.0.0.0:8000 --workers 3      
      "
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


  redis:
    image: redis:7


  worker:
    build: .
    command: celery -A project_test worker -l info --pool=threads
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
