# Generated by Django 5.2 on 2025-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RewardLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Начисленная сумма", verbose_name="Количество монет"
                    ),
                ),
                (
                    "given_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начисления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог наград",
                "verbose_name_plural": "Логи наград",
                "ordering": ["-given_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Сумма для начисления",
                        verbose_name="Количество монет",
                    ),
                ),
                (
                    "execute_at",
                    models.DateTimeField(
                        help_text="Дата/время начисления награды",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID задачи Celery"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отложенная награда",
                "verbose_name_plural": "Отложенные награды",
                "ordering": ["-execute_at"],
            },
        ),
    ]
